pipeline {
  agent any

  tools {
    maven 'test-maven'
  }

  stages {
    stage ('Build') {
      steps {
        // echo 'First step towards pipeline project'/
        bat 'mvn clean package'
      }

      post {
        success {
          archiveArtifacts artifacts: '**/target/*.war'
        }
      }
    }

    // stage ('Test') {
    //   steps {
    //     echo 'First step towards pipeline project test'
    //   }
    // }

    // stage ('Deploy') {
    //   steps {
    //     echo 'First step towards pipeline project deploy'
    //   }
    // }

  }
}